name: Playwright Tests

run-name: |
  Suite: ${{ inputs.suite }} | Env: ${{ inputs.environment }} | Browser: ${{ inputs.browser }} | Run_id: #${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Select a test suite'
        required: true
        default: ''
        type: choice
        options:
          - smoke
          - regression

      environment:
        description: 'Select environment'
        required: true
        default: ''
        type: choice
        options:
          - testing
          - staging

      browser:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

      grep:
        description: 'Optional tag filter (e.g. @login, @checkout)'
        required: false
        default: ''
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: |
          echo "Starting Playwright Browser installation..."
          npx playwright install ${{ github.event.inputs.browser }}
          echo "Playwright Browser installation finished"

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          if [ -z "${{ github.event.inputs.grep }}" ]; then
            npx playwright test --project=${{ github.event.inputs.environment }}-${{ github.event.inputs.browser }} --grep @${{ github.event.inputs.suite }}
          else
            npx playwright test --project=${{ github.event.inputs.environment }}-${{ github.event.inputs.browser }} --grep @${{ github.event.inputs.suite }} --grep "${{ github.event.inputs.grep }}"
            fi

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report --single-file

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: html-report
          path: html-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
